spring.application.name=api-gateway
server.port=1997

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**

spring.cloud.gateway.routes[1].id=restaurant-service
spring.cloud.gateway.routes[1].uri=lb://restaurant-service


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**,/api/salaries/**,/api/email/**,/api/attendance/**

spring.cloud.gateway.routes[1].predicates[0]=Path=/api/menu-items/**,/api/orders/**,/api/tables/**,/api/inventory/**,/api/sales/**,/api/order-items/**,/api/payments/**,/api/discounts/**
